SKAFFOLD_DEFAULT_REPO ?= ghcr.io/mjpitz
CWD = $(shell pwd)
VERSION ?= latest

define HELP_TEXT
Welcome to {{ .Name }}!

Targets:
  help             provides help text

  docker           rebuild the {{ .Name }} docker container
  docker/release   releases {{ .Name }} (will likely move)

  legal            prepends legal header to source code
  test             run tests
  dist             recompiles {{ .Name }} binaries

endef
export HELP_TEXT

help:
	@echo "$$HELP_TEXT"

docker: .docker
.docker:
	docker build . \
		--tag $(SKAFFOLD_DEFAULT_REPO)/{{ .Name }}:latest \
		--tag $(SKAFFOLD_DEFAULT_REPO)/{{ .Name }}:$(VERSION) \
		--file ./cmd/{{ .Name }}/Dockerfile

docker/release:
	docker buildx build . \
		--platform linux/amd64,linux/arm64 \
		--label "org.opencontainers.image.source=https://github.com/mjpitz/{{ .Name }}" \
		--label "org.opencontainers.image.version=$(VERSION)" \
		--label "org.opencontainers.image.licenses={{ .Config.License }}" \
		--label "org.opencontainers.image.title={{ .Name }}" \
		--label "org.opencontainers.image.description=" \
		--tag $(SKAFFOLD_DEFAULT_REPO)/{{ .Name }}:latest \
		--tag $(SKAFFOLD_DEFAULT_REPO)/{{ .Name }}:$(VERSION) \
		--file ./cmd/{{ .Name }}/Dockerfile \
		--push

# actual targets

legal: .legal
.legal:
	addlicense -f ./legal/header.txt -skip yaml -skip yml .

test:
	go test -v -race -coverprofile=.coverprofile -covermode=atomic ./...

dist: .dist
.dist:
	sh ./scripts/dist-go.sh

# useful shortcuts for release

tag/release:
	npm version "$(shell date +%y.%m.0)"
	git push --follow-tags

tag/patch:
	npm version patch
	git push --follow-tags
